vim.loader.enable()
-- In your config before loading plugins
vim.opt.runtimepath:prepend(vim.fn.stdpath("data") .. "/lazy/nvim-treesitter")

require("user.autocmds")
require("user.options")
require("user.lazy")
require("user.git")
require("user.lsp")
require("user.colorscheme")
require("user.treesitter")
require("user.telescope")
require("user.mini")
-- require("user.cmp")
require("user.blink")
-- require("user.minuet")
require("user.nvimtree")
require("user.lualine")
require("user.indentblankline")
require("user.keymaps")
require("user.noice")
require("user.toggleterm")
require("user.ufo")
require("user.leap")
-- require("user.conform")
require("user.null_ls")
require("user.bufferline")
require("user.colorizer")
require("user.snippets")
require("user.trouble")
-- require("user.vimade")
require("user.transparent")
require("user.cord")
