backend = "glx"
vsync = true

fading = true;
fade-delta = 6;

fade-in-step = 0.03;
fade-out-step = 0.03;

shadow-exclude = [ "! _IS_FLOATING@:32c = 1" ];

wintypes: {
    dock = {
        shadow = false;
        opacity = 1.0;
        focus = true;
      }
  }
